//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatriculasLaboratorio.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IService3")]
    public interface IService3 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService3/RegistroAlumno", ReplyAction="http://tempuri.org/IService3/RegistroAlumnoResponse")]
        void RegistroAlumno(string grupoSeleccionado, string cui, string apellidos, string nombres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService3/RegistroAlumno", ReplyAction="http://tempuri.org/IService3/RegistroAlumnoResponse")]
        System.Threading.Tasks.Task RegistroAlumnoAsync(string grupoSeleccionado, string cui, string apellidos, string nombres);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService3Channel : MatriculasLaboratorio.ServiceReference3.IService3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service3Client : System.ServiceModel.ClientBase<MatriculasLaboratorio.ServiceReference3.IService3>, MatriculasLaboratorio.ServiceReference3.IService3 {
        
        public Service3Client() {
        }
        
        public Service3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistroAlumno(string grupoSeleccionado, string cui, string apellidos, string nombres) {
            base.Channel.RegistroAlumno(grupoSeleccionado, cui, apellidos, nombres);
        }
        
        public System.Threading.Tasks.Task RegistroAlumnoAsync(string grupoSeleccionado, string cui, string apellidos, string nombres) {
            return base.Channel.RegistroAlumnoAsync(grupoSeleccionado, cui, apellidos, nombres);
        }
    }
}
